service: crypto-dashboard-frontend

frameworkVersion: '3'

provider:
    name: aws
    runtime: nodejs16.x
    stage: ${opt:stage, 'dev'}
    region: ${opt:region, 'ap-northeast-1'}

plugins:
    - serverless-finch

custom:
    client:
        bucketName: crypto-dashboard-frontend
        distributionFolder: build/
        indexDocument: index.html
        errorDocument: index.html
